export const Genders = ['MALE', 'FEMALE']
export const ViolenceTypes = ['PHYSICAL', 'PSYCHOLOGICAL', 'SEXUAL', 'ECONOMIC', 'STALKING', 'OTHER']
export const Districts = ['ALATAU', 'ALMALY', 'AUEZOV', 'BOSTANDYK', 'ZHETISU', 'MEDEU', 'NAURYZBAY', 'TURKSIB']
export const LocationTypes = ['HOME', 'APARTMENT', 'WORKPLACE', 'PUBLIC_PLACE', 'UNKNOWN', 'OTHER']
export const TimeOfDay = ['MORNING', 'AFTERNOON', 'EVENING', 'NIGHT']
export const SocialStatuses = ['EMPLOYED', 'UNEMPLOYED', 'STUDENT', 'RETIRED', 'HOUSEWIFE', 'MINOR', 'DISABLED', 'IMMIGRANT', 'HOMELESS', 'UNKNOWN']
export const AggressorRelations = ['SPOUSE', 'EX_SPOUSE', 'PARTNER', 'EX_PARTNER', 'PARENT', 'SIBLING', 'CHILD', 'FRIEND', 'STRANGER', 'NEIGHBOR', 'EMPLOYER', 'TEACHER', 'LAW_ENFORCEMENT', 'OTHER', 'UNKNOWN']
export const Authorities = ['POLICE', 'MEDICAL', 'SOCIAL_SERVICES', 'NGO', 'COURT', 'HOTLINE', 'SCHOOL_ADMIN', 'LOCAL_GOVERNMENT', 'HUMAN_RIGHTS_ORG', 'NONE', 'OTHER']
export const ActionTaken = ['SHELTER', 'PSYCHOLOGIST', 'POLICE', 'MEDICAL_ASSISTANCE', 'PSYCHOLOGICAL_SUPPORT', 'SHELTER_PROVIDED', 'LEGAL_SUPPORT', 'RELOCATION', 'RESTRAINING_ORDER', 'CASE_OPENED', 'FOLLOW_UP_SCHEDULED', 'OTHER']

export const ReportStatuses = ['PENDING', 'APPROVED', 'REJECTED']

export const ReportYears = [
  'Y2015',
  'Y2016',
  'Y2017',
  'Y2018',
  'Y2019',
  'Y2020',
  'Y2021',
  'Y2022',
  'Y2023',
  'Y2024',
  'Y2025'
]

export const Sources = [
  'NATIONAL_STATISTICS',
  'LOCAL_ADMINISTRATION',
  'MINISTRY_OF_JUSTICE',
  'CIVIL_REGISTRY',
  'OTHER'
]